name: spotify
description: "A new Flutter project."
 
 
publish_to: 'none'  


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'



#   DEPENDENCIES
 
dependencies:
  flutter:
    sdk: flutter

   
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0


   
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  google_fonts: ^6.2.1



   
  get: ^4.6.6
  get_storage: ^2.1.1 
  device_preview: ^1.2.0
  google_nav_bar: ^5.0.6
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


 
flutter:
  uses-material-design: true


   
  assets:
    - assets/images/
    - assets/fonts/
   
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets\fonts\Ubuntu-Light.ttf
          weight: 300
        - asset: assets\fonts\Ubuntu-Regular.ttf
          weight: 400
        - asset: assets\fonts\Ubuntu-Italic.ttf
          style: italic
        - asset: assets\fonts\Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Ubuntu-Medium.ttf
          weight: 500
        - asset: assets\fonts\Ubuntu-Bold.ttf
          weight: 800
