// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcYNK5yCL1loY59ZY04KjpcWz5p9SBPLM',
    appId: '1:603335133311:web:6a3242889dc8fba361974a',
    messagingSenderId: '603335133311',
    projectId: 'muzika01',
    authDomain: 'muzika01.firebaseapp.com',
    storageBucket: 'muzika01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWstSaKECROXDCW0wwz7glEl2_yropsdQ',
    appId: '1:603335133311:android:848356c3208278ca61974a',
    messagingSenderId: '603335133311',
    projectId: 'muzika01',
    storageBucket: 'muzika01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimUsttXJynC_F-ZqeF_tswNpSkSNoTNE',
    appId: '1:603335133311:ios:2bb016d8d0e21cb361974a',
    messagingSenderId: '603335133311',
    projectId: 'muzika01',
    storageBucket: 'muzika01.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBimUsttXJynC_F-ZqeF_tswNpSkSNoTNE',
    appId: '1:603335133311:ios:2bb016d8d0e21cb361974a',
    messagingSenderId: '603335133311',
    projectId: 'muzika01',
    storageBucket: 'muzika01.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcYNK5yCL1loY59ZY04KjpcWz5p9SBPLM',
    appId: '1:603335133311:web:b4a0ea56ae1ebdef61974a',
    messagingSenderId: '603335133311',
    projectId: 'muzika01',
    authDomain: 'muzika01.firebaseapp.com',
    storageBucket: 'muzika01.appspot.com',
  );
}
